/**
 * HiveCode Auto-Initialization
 *
 * Ensures HiveCode is properly initialized for a project.
 * Safe to call multiple times (idempotent).
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync, chmodSync } from 'node:fs';
import { join } from 'node:path';

interface ProjectConfig {
  projectRoot: string;
  projectName: string;
  hiveDir: string;
}

/**
 * Ensure HiveCode is initialized for the project.
 * Creates necessary directories and hooks if they don't exist.
 * Safe to call multiple times.
 *
 * @returns true if initialization was performed, false if already initialized
 */
export function ensureHiveInitialized(config: ProjectConfig, silent = false): boolean {
  const log = silent ? () => {} : console.log;
  let didInit = false;

  // 1. Create .hive directory structure
  const tasksDir = join(config.hiveDir, 'tasks');
  const statusDir = join(config.hiveDir, 'status');

  if (!existsSync(tasksDir)) {
    mkdirSync(tasksDir, { recursive: true });
    didInit = true;
  }
  if (!existsSync(statusDir)) {
    mkdirSync(statusDir, { recursive: true });
    didInit = true;
  }

  // 2. Create .claude/hooks directory and hook script
  const hooksDir = join(config.projectRoot, '.claude', 'hooks');
  const hookScript = join(hooksDir, 'inject-hive-role.sh');

  if (!existsSync(hookScript)) {
    mkdirSync(hooksDir, { recursive: true });
    writeFileSync(hookScript, getHookScriptContent(), { mode: 0o755 });
    didInit = true;
    log('  ✓ Created HiveCode hook script');
  }

  // 3. Create/update .claude/settings.json if hook not configured
  const settingsFile = join(config.projectRoot, '.claude', 'settings.json');
  if (!existsSync(settingsFile)) {
    const settings = {
      hooks: {
        SessionStart: [
          {
            matcher: 'startup',
            hooks: [
              {
                type: 'command',
                command: '"$CLAUDE_PROJECT_DIR/.claude/hooks/inject-hive-role.sh"',
                statusMessage: 'Loading Hive role...',
              },
            ],
          },
        ],
      },
    };
    writeFileSync(settingsFile, JSON.stringify(settings, null, 2));
    didInit = true;
    log('  ✓ Created .claude/settings.json with HiveCode hook');
  } else {
    // Check if hook is already configured
    try {
      const content = readFileSync(settingsFile, 'utf-8');
      if (!content.includes('inject-hive-role.sh')) {
        // Settings exists but hook not configured - warn user
        if (!silent) {
          log('\x1b[33m  ⚠️  .claude/settings.json exists but HiveCode hook not configured\x1b[0m');
          log('     Run `hivecode init` to see manual configuration instructions');
        }
      }
    } catch {
      // Ignore read errors
    }
  }

  // 4. Create assignment.md if not exists
  const assignmentFile = join(config.hiveDir, 'assignment.md');
  if (!existsSync(assignmentFile)) {
    writeFileSync(assignmentFile, getAssignmentTemplate(config.projectName));
    didInit = true;
  }

  return didInit;
}

/**
 * Generate the hook script content
 */
function getHookScriptContent(): string {
  return `#!/bin/bash
#
# inject-hive-role.sh - Hive role auto-injection
#
# Auto-generated by HiveCode
#

set -e

INPUT=$(cat)
CWD=$(echo "$INPUT" | jq -r '.cwd // empty')
[ -z "$CWD" ] && CWD=$(pwd)

# Detect Worker worktree (path ends with /worker-N)
if echo "$CWD" | grep -qE '/worker-[0-9]+$'; then
    WORKER_ID=$(basename "$CWD" | sed 's/worker-//')
    cat << EOF
<hive-role>
You are Hive Worker-\${WORKER_ID}.

Your responsibilities:
1. Read .hive/tasks/worker-\${WORKER_ID}.md to get your task
2. Focus on completing the assigned task
3. After completion, run lint/test to verify
4. Update .hive/status/worker-\${WORKER_ID}.json

Status file format:
{
  "status": "idle|coding|testing|reviewing|ready_for_review|approved",
  "branch": "feature/xxx",
  "current": "Current work description",
  "percent": 50,
  "subagent": {
    "name": "lint|test|code-review",
    "status": "running|passed|failed",
    "message": "Optional message"
  }
}

Start by reading your task file.
</hive-role>
EOF
    exit 0
fi

# Detect Queen (project root with .hive directory)
if [ -d "$CWD/.hive" ]; then
    cat << EOF
<hive-role>
You are Hive Queen (coordinator).

Your responsibilities:
1. Create plans and distribute tasks to .hive/tasks/worker-N.md
2. Monitor .hive/status/ to track Worker progress
3. When PRs are ready, have a Worker run code-reviewer subagent
4. Coordinate merges and resolve conflicts

You do NOT write code directly. Focus on coordination and decisions.

Worker management commands:
- hivecode workers up       Start all 4 Workers
- hivecode workers down     Stop all Workers
- hivecode workers restart N  Restart a specific Worker
- hivecode dashboard        Monitor Workers in TUI
- hivecode status           Show Worker status

Workers are persistent and maintain context. Assign tasks based on:
- Current workload and expertise
- Task dependencies
- Code review needs (1-2 Workers can review others)

Start by reading .hive/assignment.md to understand the current task allocation.
</hive-role>
EOF
    exit 0
fi

exit 0
`;
}

/**
 * Generate assignment.md template
 */
function getAssignmentTemplate(projectName: string): string {
  return `# Task Assignment

## Project: ${projectName}

## Overview

Describe the overall task here.

## Workers

| Worker | Task | Branch | Status |
|--------|------|--------|--------|
| Worker-1 | — | — | idle |
| Worker-2 | — | — | idle |
| Worker-3 | — | — | idle |
| Worker-4 | — | — | idle |

## Notes

- Edit this file to plan task distribution
- Create .hive/tasks/worker-N.md for each Worker's detailed task
- Workers will read their task files automatically
`;
}
